[package]
name = "surfmol-molrender"
version = "0.1.0"
edition = "2021"

[dependencies]
surfmol-common = { path = "../common" }
surfmol-topology = { path = "../topology" }
wgpu = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
nalgebra = { workspace = true }

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
