[package]
name = "surfmol-apps"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "mol_browser"
path = "src/mol_browser.rs"

[[bin]]
name = "editor"
path = "src/editor.rs"

[dependencies]
surfmol-forcefields = { path = "../forcefields" }
surfmol-common = { path = "../common" }
surfmol-topology = { path = "../topology" }
surfmol-molrender = { path = "../molrender" }
wgpu = { workspace = true }
pollster = { workspace = true }
winit = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
egui-winit = { workspace = true }
egui-wgpu = { workspace = true }
egui_extras = "0.29"
glam = { workspace = true }
nalgebra = { workspace = true }
image = "0.25"
