[package]
name = "molgui"
version = "0.1.0"
edition = "2021"
description = "GUI toolkit: TrackballCam, KekuleEditor, MolThumbnailer, gizmos"

[dependencies]
numcore = { workspace = true }
moltopo = { workspace = true }
molrender = { workspace = true }
wgpu = { workspace = true }
pollster = { workspace = true }
glam = { workspace = true }
egui = { workspace = true }
arboard = { workspace = true }
[dev-dependencies]
image = { workspace = true }
